name: SKY LANDISH
favicon: null
layout_spectrum: 0.47633
typography_spectrum: 0.05499
title: SKY A LANDISH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
