name: SKY LANDISH
favicon: null
layout_spectrum: 0.9768687223549932
typography_spectrum: 0.9941208811942488
title: SKY A LANDISH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.07398587837815285
  lightness: 0.03571996232494712
  saturation: 0.7917305594310164
  rhythmicContrast: 0.6768790618516505
purpose: []
