name: SKY LANDISH
favicon: null
layout_spectrum: 0.47633
typography_spectrum: 0.83373
title: SKY A LANDISH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#201827'
    - '#d3bdaf'
    - '#9e6a42'
    - '#535e13'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
