name: SKY LANDISH
favicon: null
layout_spectrum: 0.75845
typography_spectrum: 0.66948
title: SKY A LANDISH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#657888'
    - '#9c0a13'
    - '#d68f63'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
